name: sorface-quickstart

services:
  redis:
    container_name: "redis"
    build:
      context: datastorage.redis
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - datastorage.redis/.docker.redis.env

  postgresql:
    container_name: "postgresql"
    build:
      context: datastorage.postgresql
      dockerfile: Dockerfile
    env_file:
      - datastorage.postgresql/.docker.pgsql.env

  be_passport:
    container_name: "be_passport"
    build:
      context: service.passport/backend/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: 'feature/gateway'
        MAVEN_PROFILE: 'passport.development'
    restart: always
    depends_on:
      - redis
      - postgresql
    env_file:
      - service.passport/backend/.env

  be_gateway:
    container_name: "be_gateway"
    build:
      context: service.gateway/backend/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: 'master'
        MAVEN_PROFILE: 'gateway.docker'
    restart: always
    depends_on:
      - be_passport
    env_file:
      - service.gateway/backend/.env
    extra_hosts:
      - "api.idp.sorface.local:host-gateway"

  fe_id:
    container_name: "fe_id"
    build:
      context: service.passport/frontend/id/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: master
        REACT_APP_GATEWAY_URL: 'http://localhost:9030/passport'
        REACT_APP_PASSPORT_PREFIX: '/passport'
        REACT_APP_BUILD_HASH: '1.0.0-Docker'
    restart: always

  fe_passport:
    container_name: "fe_passport"
    build:
      context: service.passport/frontend/passport/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: master
        REACT_APP_BACKEND_URL: 'http://api.idp.sorface.local:8023/passport'
        REACT_APP_PROFILE_PAGE: 'http://id.sorface.local:8023/account'
        REACT_APP_BUILD_HASH: '1.0.0-Docker'
    restart: always

  nginx:
    container_name: "proxy"
    build:
      context: proxy
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - postgresql
      - be_passport
      - be_gateway
      - fe_id
      - fe_passport
    ports:
      - "8023:80"