name: sorface-quickstart

services:

  redis:
    container_name: "redis"
    build:
      context: datastorage.redis
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - datastorage.redis/.docker.redis.env

  postgresql:
    container_name: "postgresql"
    build:
      context: datastorage.postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - datastorage.postgresql/.docker.pgsql.env

  backend-passport:
    container_name: "backend.passport"
    build:
      context: service.passport/backend/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: 'feature/gateway'
        MAVEN_PROFILE: 'passport.docker'
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgresql
    env_file:
      - service.passport/backend/.env

  backend-gateway:
    container_name: "backend.gateway"
    build:
      context: service.gateway/backend/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: 'master'
        MAVEN_PROFILE: 'gateway.docker'
    restart: always
    ports:
      - "9000:9000"
#    depends_on:
#      - redis
#      - postgresql
#      - backend-passport
    env_file:
      - service.gateway/backend/.env

  backend-interview:
    container_name: "backend.interview"
    build:
      context: service.interview/backend/
      dockerfile: Dockerfile
      args:
        GITHUB_BRANCH: 'bugfix/#471'
    restart: always
    depends_on:
      - redis
      - postgresql
      - backend-passport
      - backend-gateway
    env_file:
      - service.interview/backend/.env

  frontend.web.id:
    container_name: "frontend.web.interview"
    build:
      context: service.interview/frontend/
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: 'http://localhost:9030/passport'
        REACT_APP_VERSION: 1.0.0-Develop
        PORT: 9030
    ports:
      - "9030:80"
    restart: always

  frontend.web.passport:
    container_name: "frontend.web.passport"
    build:
      context: service.passport/frontend/
      dockerfile: service.passport/frontend/passport/Dockerfile
      args:
        REACT_APP_BACKEND_URL: 'http://localhost:8080'
        REACT_APP_VERSION: 1.0.0-Develop
        REACT_APP_PROFILE_PAGE: http://localhost:9030/account
    ports:
      - "3001:80"
    restart: always

  frontend.web.interview:
    container_name: "frontend.web.interview"
    build:
      context: service.interview/frontend/
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: 'http://localhost:3000/api/product/interview'
        REACT_APP_LOGIN_URL: 'http://localhost:3000/oauth2'
        REACT_APP_LOGOUT_URL: 'http://localhost:3000/logout'
        REACT_APP_PASSPORT_URL: 'http://localhost:3000/passport/api'
        REACT_APP_WS_URL: 'ws://localhost:9000/ws'
        REACT_APP_BUILD_HASH: '1.0.0-Develop'
        PORT: 3000
    ports:
      - "3000:80"
    restart: always